import React from 'react';

export const metadata = {
    title: "Dragon News About",
    description: "Generated by create next app",
};

const AboutPage = () => {
    return (
        <div>
            About
        </div>
    );
};

export default AboutPage;